
pruning_parameters:
  disable_pruning_for_layers: # Disable pruning for these layers, even if enable_pruning is true
    - 
  enable_pruning: true
  pruning_method: continual_learning
  threshold: 0.3
  t_delta: 20
quantization_parameters:
  default_integer_bits: 0.
  default_fractional_bits: 7.
  enable_quantization: false
  hgq_gamma: 0.0003
  layer_specific: []
  use_high_granularity_quantization: false
  use_real_tanh: false
  use_symmetric_quantization: false
training_parameters:
  batch_size: 256
  cosine_tmax: 200
  epochs: 150
  fine_tuning_epochs: 0
  gamma: 0.1
  l2_decay: 0.0001
  label_smoothing: 0.0
  lr: 0.01
  lr_schedule: cosine
  milestones:
  - -1
  - -1
  momentum: 0.9
  optimizer: sgd
  plot_frequency: 100
  pretraining_epochs: 0
  pruning_first: false
  rewind: never
  rounds: 1
  save_weights_epoch: -1
  threshold_decay: 0.
