pruning_parameters:
  calculate_pruning_budget: True
  disable_pruning_for_layers: # Disable pruning for these layers, even if enable_pruning is true
    -
  enable_pruning: true
  M: null
  N: null
  pruning_method: wanda
  threshold_decay: 0.
  sparsity: 0.90
  t_delta: 100
  t_start_collecting_batch: 100
quantization_parameters:
  default_integer_bits: 0.
  default_fractional_bits: 7.
  enable_quantization: true
  hgq_gamma: 0.0003
  hgq_heterogeneous: True
  layer_specific: []
  use_high_granularity_quantization: false
  use_real_tanh: false
  use_relu_multiplier: true
  use_symmetric_quantization: false
training_parameters:
  epochs: 200
  fine_tuning_epochs: 0
  pretraining_epochs: 50
  pruning_first: false
  rewind: never
  rounds: 1
  save_weights_epoch: -1
batch_size: 64
cosine_tmax: 200
gamma: 0.1
l2_decay: 0.0001
label_smoothing: 0.0
lr: 0.01
lr_schedule: cosine
milestones:
- -1
- -1
momentum: 0.9
optimizer: sgd
plot_frequency: 100
